version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /media/usbhd1/docker/homarr/configs:/app/data/configs
      - /media/usbhd1/docker/homarr/icons:/app/public/icons
    ports:
      - '7575:7575'
