---
version: "2.1"
services:

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /media/usbhd1/docker/duplicati>:/config
      - /mnt:/backups
      - /media/usbhd1/docker:/source
    ports:
      - 8200:8200
    restart: unless-stopped
