version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/Berlin
    volumes:
      - /media/usbhd1/docker/radarr:/config
      - /media/usbhd1/docker-data/media/peliculas:/movies #optional
      - /media/usbhd1/docker-data/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
networks: {}
