version: "3"
services:

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/Berlin
    volumes:
      - /media/usbhd1/docker/readarr:/config
      - /media/usbhd1/docker/media/books:/books #optional
      - /media/usbhd1/docker/downloads:/downloads #optional
    ports:
      - 8788:8787
    restart: unless-stopped
