version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:999
    network_mode: 'host'
    volumes:
      - /media/usbhd1/docker/jellyfin:/config
      - /media/usbhd1/docker/jellyfin/cache:/cache
      - /media/usbhd1/docker/media/:/media
      #- /path/to/media2:/media2:ro
    ports:
      - 8090:8092
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
