version: "3"
services:

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/Berlin
    volumes:
      - /media/usbhd1/docker/sonarr:/config
      - /media/usbhd1/docker-media/media/series:/tv #optional
      - /media/usbhd1/docker-media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
