version: "3"
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      #- PUID=1000
      #- PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /media/usbhd1/docker/plex:/config
      - /media/usbhd1/docker-media/media/series:/tv
      - /media/usbhd1/docker-media/media/peliculas:/movies
      - /media/usbhd1/docker-media/media/music:/music
    restart: unless-stopped
