version: "3"
services:

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/Berlin
    volumes:
      - /media/usbhd1/docker/lidarr:/config
      - /media/usbhd1/docker/media/music:/music #optional
      - /media/usbhd1/docker/downloads:/downloads #optional
    ports:
      - 8687:8686
    restart: unless-stopped
