---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=0
      - PGID=999
      - TZ=Europe/London
    volumes:
      - /media/usbhd1/docker/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
