version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Paris
       ports:
            - 5058:5055
       volumes:
            - /media/usbhd1/docker/jellyseerr:/app/config
       restart: unless-stopped
